src/blog/urls.py
import debug_toolbar

# from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

from myblog.sitemaps import PostSitemap


sitemaps = {'posts': PostSitemap, }

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('myblog/', include('myblog.urls', namespace='myblog')),
    path(
        'sitemap.xml', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    )
]

src/myblog/urls.py
from django.urls import path

from . import views
from .feeds import LatestPostsFeed


app_name = 'myblog'

urlpatterns = [
    path('', views.PostList, name='post_list'),
    # additional URL to list posts by tag
    path('tag/<slug:tag_slug>/', views.PostList, name='post_list_by_tag'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.SinglePost, name='single_post'),
    path('<int:post_id>/share', views.PostShare, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
    ]

src/myblog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone

from taggit.managers import TaggableManager


# create a custom manager to retrieve all posts with the published status

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):

    # the default manger
    objects = models.Manager()
    # custom manager
    published = PublishedManager()

    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)

    # a field that will be used in urls
    slug = models.SlugField(max_length=250, unique_for_date='publish')

    # OneToMany relationship (each post is written by user and every user can write many posts)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_post')

    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    # to be able to add, retrieve and remove tags from Post objects
    tags = TaggableManager()

    class Meta:
        # sort 'published' in descending order, so post published recently will appear first
        ordering = ('-publish',)

    # make 'title' human-readable representation
    def __str__(self):
        return self.title

    # build the canonical URLs for Post objects
    def get_absolute_url(self):
        return reverse('myblog:single_post',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug]
                       )


class Comment(models.Model):

    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=50)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created', )

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

src/myblog/forms.py
from django import forms

from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()

src/myblog/views.py
from django.contrib.postgres.search import TrigramSimilarity
from django.core.mail import send_mail
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView
# from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank

from myblog.models import Post

from taggit.models import Tag

from .forms import CommentForm, EmailPostForm, SearchForm


class PostListView(ListView):

    # build a generic QuerySet
    queryset = Post.published.all()
    # use conrext variable 'posts' for a query results
    context_object_name = 'posts'
    # 3 posts in each page
    paginate_by = 3
    # use a custom template name
    template_name = 'blog/post/list.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['GET_PARAMS'] = '&'.join(
            f'{key}={value}'
            for key, value in self.request.GET.items()
            if key != 'page'
        )
        context['object_count'] = context['object_list'].count()
        return context


def SinglePost(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        slug=post,
        status='published',
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )
    ''' get all active comments for this post using the manager 'comments'
     that was created with a related_name in the Comment model '''
    comments = post.comments.filter(active=True)

    # initialize a variable to save a new comment later
    new_comment = None
    # check if a new comment was added
    if request.method == 'POST':
        # instantiate the form using the submitted data and validate it
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid:
            # create Comment object but don't save it to DB
            new_comment = comment_form.save(commit=False)
            # assign the current post to this comment
            new_comment.post = post
            new_comment.save()
    # build a form instance if the view is called by a GET request
    else:
        comment_form = CommentForm()
    # retrieve a list of ids for all tags of the current post. value_list returns a tuple of ids
    post_tags_ids = post.tags.values_list('id', flat=True)
    # get all posts that contain any of these tags, excluding the current post
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    # use Count() to generate the number of tags shared with all the tags queried
    # to display resent posts first for the post with the same number of shared tags
    # retrieve only the first four posts
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    return render(request, 'blog/post/single.html', {
        'post': post,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
        'similar_posts': similar_posts
        })


def PostShare(request, post_id):

    # retrieve the post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    # check if the form is submitted
    if request.method == 'POST':
        # create a form instance using data from the request.POST
        form = EmailPostForm(request.POST)
        # validate form's fields
        if form.is_valid():
            cleaned_data = form.cleaned_data
            # send email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cleaned_data['name']} recommends you to read " \
                      f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{cleaned_data['name']}\'s comments: {cleaned_data['comments']}"
            send_mail(subject, message, 'djangoproject20@gmail.com', [cleaned_data['to']])
            sent = True
    else:
        # having a Get request create a new form instance to display an empty form in the template
        form = EmailPostForm
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


def PostList(request, tag_slug=None):
    # the optional parameter 'tag_slug' will be passed in the URL

    object_list = Post.published.all()
    tag = None

    # check if there's a given tag_slug
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        # filter the list of the posts by the ones that contain the given tag
        object_list = object_list.filter(tags__in=[tag])

    # instantinate a paginator class with a number of objects to be displayed
    paginator = Paginator(object_list, 3)  # 3 posts in each page
    page = request.GET.get('page')  # get the current page
    try:
        posts = paginator.page(page)  # obtain the objects of a desired page
    except PageNotAnInteger:  # if the page isn't an integer deliver the first one
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(
        request,
        'blog/post/list.html',
        {'page': page,  # pass page number and retrieved objects to the template
         'posts': posts,
         'tag': tag},
    )


def post_search(request):
    # instantiate the SearchForm form
    form = SearchForm()
    query = None
    results = []
    # check if the form is submitted, looking for a query param in the request.Get dict
    # using the GET method, so that the resulting URL includes the query param
    if 'query' in request.GET:
        # instantiate the submitted form with the submitted GET data
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']

            # search_vector = SearchVector('title', weight='A') +\
            #                 SearchVector('body', weight='B')
            # search_query = SearchQuery(query)
            # results = Post.published.annotate(
            #    search=search_vector, rank=SearchRank(search_vector, search_query))\
            #    .filter(rank__gte=0.3).order_by('-rank')

            results = Post.published.annotate(
                similarity=TrigramSimilarity('title', query),)\
                .filter(similarity__gt=0.1).order_by('-similarity')
    return render(request, 'blog/post/search.html',
                  {'form': form, 'query': query, 'results': results})

src/myblog/templates/blog/post/latest_posts.html
<ul>
    {%  for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

src/myblog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}My Blog {% endblock title %}

{% block content %}
    <h1>My Blog</h1>
        {% if tag %}
            <h2>Posts tagged with {{ tag.name }}</h2>
        {% endif %}
        {% for post in posts %}
            <h2>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h2>
            <p class="tags">Tags:
                {% for tag in post.tags.all %}
                    <a href="{% url 'myblog:post_list_by_tag' tag.slug %}">
                        {{tag.name}}
                    </a>
                    {%if not forloop.last %}, {% endif %}
                {% endfor %}
            </p>
            <p class="date">
                Pulished {{post.publish}} by {{post.author}}
            </p>
            {{ post.body|markdown|truncatewords:30 }}
            <p>
                <a href="{% url 'myblog:post_share' post.id %}">
                    Share this post
                </a>
            </p>
        {% endfor %}

    {% include "blog/pagination.html" with page=posts %}

{% endblock content %}

src/myblog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}Search{% endblock %}

{% block content %}
    {% if query %}
        <h1>Posts containing "{{ query }}"</h1>
            <h3>
                {% with results.count as total_results %}
                    Found {{ total_results }} result{{ total_results|pluralize }}
                {% endwith %}
            </h3>
            {% for post in results %}
                <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
                {{ post.body|markdown|truncatewords_html:5 }}
                {% empty %}
                    <p>There are no results for your query.</p>
            {% endfor %}
            <p><a href="{% url 'myblog:post_search' %}">Search again</a></p>
    {% else %}
        <h1>Search for posts</h1>
        <form method="get">
        {{ form.as_p }}
        <input type="submit" value="Search">
        </form>
    {% endif %}
{% endblock %}

src/myblog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock title %}

{% block content %}
   {% if sent %}
        <h1>E-mail successfully sent</h1>
            <p>
                "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}
            </p>
   {% else %}
        <h1>Share "{{ post.title }}" by e-mail </h1>
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
   {% endif %}
{% endblock content %}

src/myblog/templates/blog/post/single.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock title %}
{% block content %}
    <h1>{{ post.title }}</h1>
            <p class="date">
                Pulished {{post.publish}} by {{post.author}}
            </p>
            {{ post.body|markdown }}

    <h2>Similar posts</h2>
        {% for post in similar_posts %}
            <p>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </p>
            {% empty %}
                There are no similar posts yet
        {% endfor %}

    {% with comments.count as total_comments %}
        <h3>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h3>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
        {% empty %}
            <p>There aren't any comments yet.</p>
    {% endfor %}

    {% if new_comment%}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment.</h2>
        <form method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {% endif %}
{% endblock content %}